routes:
  /:
    controller: channel
    filter: tag:blog
  /art/:
    controller: channel
    filter: tag:art
    template: art
    data: page.art
  /photography/:
    controller: channel
    filter: tag:photography
    template: photography
    data: page.photography

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
